apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/muratbekov3/devsecops_2
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true