name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        cd app-source
        docker build -t app:${{ github.sha }} .

    - name: Scan image (Trivy)
      run: trivy image app:${{ github.sha }}

    - name: Push to DockerHub
      run: |
        docker tag app:${{ github.sha }} muratbekov3/devsecops-app:${{ github.sha }}
        docker push muratbekov3/devsecops-app:${{ github.sha }}